### ISSUE TITLE
'db' propery must be specified in config file

### ISSUE THREAD

**Issue by Karreg** [karimsa/patrol#41]
Hello,

When using the documented command, we end up with this error:

```
2023/01/05 15:10:46 Initializing with SHELL = /bin/sh
'db' propery must be specified in config file
```

Tested with the documented command :

```bash
docker run -d \
	--name patrol \
	--restart=on-failure \
	-v "$PWD:/data" \
	-p 8080:8080 \
	--log-driver json-file \
	--log-opt max-size=100m \
	ghcr.io/karimsa/patrol:latest \
	run \
	--config ./config/patrol.yml
```

Also tested with docker-compose:

```yaml
version: "3.9"

services:
  monitoring:
    image: ghcr.io/karimsa/patrol:latest
    ports:
      - "8080:7080"
    configs:
      - source: patrol
        target: /patrol.yml
        mode: 0664
    command: run --config /patrol.yml

configs:
  patrol:
    file: ./config/patrol.yml
```

Content of patrol.yml:

```yaml
services:
  google:
    checks:
    - name: Internal
      cmd: 'curl -fsSL https://www.google.fr'
```

Maybe the documentation is obsolete? Thanks for your help!
